### ISSUE TITLE
MP4 file not recognised

### ISSUE THREAD

**Issue by doublex** [bangnoise/qt-flatten#2]
Error message:
Error: The file was not recognised as a QuickTime movie.

Steps to reproduce:
wget http://doppelbauer.name/huge-moov.mp4
qt-flatten -c huge-moov.mp4 dummy.mp4

Thanks a lot
Marcus

**Comment by bangnoise** [comment]
Exactly what the error message says. An MPEG-4 movie is not a QuickTime movie. I don't own a copy of the MPEG-4 spec to code to.

If you are simply interested in getting it working and don't mind losing a check for conformance, you could comment out line 525 of qt_flatten.c:

```
// if (!has_qt) result = qtf_result_file_not_movie;
```

**Comment by bangnoise** [comment]
Support for MP4 added in 44764958b6a6eebe58dc320093868298129de8b3
